### ISSUE TITLE
Dependancies and Updates

### ISSUE THREAD

**Issue by blakeusblade** [quacktacular/mac-device-id-to-model#1]
Hi,

Full disclosure. I'm not a python guy. Only a bash/shell guy...

What version of python is required on macOS to run update_models.py?

When I run the above script in macOS I get the below
ModuleNotFoundError: No module named 'requests'

I've tried with the below versions of python on macOS
2.7.16
3.10.7

While this is a great thing, its limiting factor is how frequently the models.txt is updated. Granted new models come out infrequently, but this requires humen intervension to keep this list updated. I'd be keen to have it automated where its updated on a scheduled basis like once per day/ week.

**Comment by quacktacular** [comment]
Hi @blakeusblade. This tool was created with Python 3. The error you see isn't due to a Python version incompatibility, it's because of a missing Python module (`requests`) on your machine.

The repo contains a requirements.txt which can be used to determine additional Python modules to run the script. You can install the modules by running `pip install -r requirements.txt`. You can also use pip to install modules individually like `pip install requests`. Depending on your environment you may need to use `pip3` instead of `pip`.
