### ISSUE TITLE
python script to generate models is missing imac pro model

### ISSUE THREAD

**Issue by blakeusblade** [quacktacular/mac-device-id-to-model#2]
Can you please update the python script and run to include missing model data for iMac Pro.

**Comment by blakeusblade** [comment]
the models.txt should contain this line
iMac Pro (2017)|iMacPro1,1

**Comment by quacktacular** [comment]
Hey @blakeusblade since there was only one iMac Pro the official marketing name doesn't have a year, which confused the script. I made a change that will handle cases like that.
https://github.com/quacktacular/mac-device-id-to-model/commit/e3db35e5328f0280657690b8493600bf06e425eb
It doesn't include the model year. Is that necessary for your use case? Could read parent tags to try and guess in cases like that.

**Comment by quacktacular** [comment]
Added the year string after a second pipe in models.txt.
