### ISSUE TITLE
Wrong model detected in MacBookAir7,2

### ISSUE THREAD

**Issue by kholis** [quacktacular/mac-device-id-to-model#9]
Hi,

I have `MacBook Air (13-inch, Early 2015)|MacBookAir7,2` but with your script is always detected as `MacBook Air (13-inch, 2017)|MacBookAir7,2|2017` model.

Any workaround? Thank you

**Comment by quacktacular** [comment]
Hey @kholis this approach uses the Model ID (like MacBookAir7,2 in your case) to identify the marketing name. Since they're the same there's no way to differentiate between the two programmatically. The shell script I wrote goes with the newer model since they're effectively the same machine. You could adapt it use the older one instead, or even ask the user to confirm manually if you wanted.
